import React from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import Footer from "../footer";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Third Frame",
  description: "Generated by create next app",
};
import "./thirdframe.css";
import Ship from "./ship.jpg";
import Location from "./location.jpg";
import Calender from "./calendar.jpg";
import Edit from "./edit2.jpg";
import Vector from "./Vector.jpg";
import Arrow from "./arrowdown2.jpg";
import WhiteStar from "./whiteStar.jpg";
import BlueStar from "./BlueStar.jpg";
import Frame from "./Frame.jpg";
import Plane from "./airplane.jpg";
import Ellipse from "./Ellipse.jpg";
import BlueEllipse from './blueEllipse.jpg';

export default function page() {
  return (
    <div className="thirdFrame">
      <div className="thirdFrame-nav">
        <h1>
          Ship<span>mate</span>
        </h1>
        <div className="thirdFrame-nav-div">
          <div>
            <Image src={Vector} alt="vector"></Image>
          </div>
          <button>Track shipment</button>
        </div>
      </div>

      <div className="load-div">
        <Image src={Ship} alt="ship" />
        <p>Load</p>
      </div>

      <div className="round-div">
        <div className="round-div-div">
          <div>1</div>
          <p>Search</p>
        </div>
        <div className="sidebar"></div>
        <div className="round-div-div">
          <div>2</div>
          <p>Recommended services</p>
        </div>
        <div className="sidebar"></div>
        <div className="round-div-div">
          <div>3</div>
          <p>Results</p>
        </div>
        <div className="sidebar"></div>
        <div className="round-div-div booking">
          <div></div>
          <p>Booking</p>
        </div>
      </div>

      <div className="middle-content">
        <div className="middle-inner-div">
          <div className="big-div">
            <Image src={Location} alt="location"></Image>
            <p>Delhi, 110003</p>
          </div>
          <div className="big-div">
            <Image src={Location} alt="location"></Image>
            <p>Shanghai 200080</p>
          </div>
          <div className="big-div">
            <Image src={Calender} alt="calender"></Image>
            <p>13 April 2023</p>
          </div>
          <div className="small-div">
            <Image src={Ship} alt="ship" />
            <p>114.21KG - AIR</p>
          </div>
        </div>
        <div className="sideline"></div>
        <Image src={Edit} alt="edit" className="edit"></Image>
      </div>

      <div className="linebar"></div>

      <div className="best-value-div">
        <div className="best-value-div-div">
          <p>Best Value 5-5 days. $3,121</p>
        </div>
        <p>Quickest 5-5 days. $3,121</p>
        <p>Cheapest 5-5 days. $3,121</p>
      </div>
      <p className="best">
        3 Top Quote <span>(6 in Total)</span>
      </p>
      <div className="list">
        <div className="filters">
          <p>Filters</p>
          <Image src={Arrow} alt="arrow"></Image>
        </div>
        <div className="price">
          <p>Price</p>
          <Image src={Arrow} alt="arrow"></Image>
        </div>
        <div className="modes">
          <p>Modes</p>
          <Image src={Arrow} alt="arrow"></Image>
        </div>
        <div className="seller">
          <p>Seller</p>
          <Image src={Arrow} alt="arrow"></Image>
        </div>
      </div>
      <div className="last-div">
        <div className="last-div-div1">
          <div className="last-div-left">
            <div className="last-div-left-upper">
              <div className="express-div">
                <button className="best-value">
                  {" "}
                  <Image src={Ellipse} alt="ellipse"></Image> Best value
                </button>
                <div className="express">
                  <p className="exp-p">Express</p>
                  <p className="date">Est. 5 days</p>
                </div>
              </div>
              <div className="distance">
                <div className="delhi-distance">
                  <Image src={Location} alt="location"></Image>
                  <p>110003, Delhi</p>
                </div>
                <div className="hifen"></div>
                <Image className="plane-img" src={Plane} alt="plane"></Image>
                <div className="hifen"></div>
                <div className="sanghi-distance">
                  <Image src={Location} alt="location"></Image>
                  <p>200080, Shanghai</p>
                </div>
              </div>
            </div>
            <div className="primetime">
              <div className="primetime-left">
                <Image src={Frame} alt="frame"></Image>
                <p>Primetime Worldwide</p>
              </div>
              <div className="primetime-right">
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={WhiteStar} alt="white"></Image>
              </div>
            </div>
          </div>
          <div className="last-div-sidebar"></div>
          <div className="last-div-right">
            <p className="last-div-right-p">
              $ 3,982.<span>63</span>
            </p>
            <div className="last-div-down">
              <button>Select</button>
              <p>View details</p>
            </div>
          </div>
        </div>
        <div className="last-div-div2">
          <div className="last-div-left">
            <div className="last-div-left-upper">
              <div className="express-div">
                <button className="best-value eco">
                  {" "}
                  <Image src={BlueEllipse} alt="ellipse"></Image> Eco
                </button>
                <div className="express">
                  <p className="exp-p">Express</p>
                  <p className="date">Est. 5 days</p>
                </div>
              </div>
              <div className="distance">
                <div className="delhi-distance">
                  <Image src={Location} alt="location"></Image>
                  <p>110003, Delhi</p>
                </div>
                <div className="hifen"></div>
                <Image className="plane-img" src={Plane} alt="plane"></Image>
                <div className="hifen"></div>
                <div className="sanghi-distance">
                  <Image src={Location} alt="location"></Image>
                  <p>200080, Shanghai</p>
                </div>
              </div>
            </div>
            <div className="primetime">
              <div className="primetime-left">
                <Image src={Frame} alt="frame"></Image>
                <p>Primetime Worldwide</p>
              </div>
              <div className="primetime-right">
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={WhiteStar} alt="white"></Image>
              </div>
            </div>
          </div>
          <div className="last-div-sidebar"></div>
          <div className="last-div-right">
            <p className="last-div-right-p">
              $ 3,982.<span>63</span>
            </p>
            <div className="last-div-down">
              <button>Select</button>
              <p>View details</p>
            </div>
          </div>
        </div>

        <div className="last-div-div3">
          <div className="last-div-left">
            <div className="last-div-left-upper">
              <div className="express-div">
                <button className="best-value">
                  {" "}
                  <Image src={Ellipse} alt="ellipse"></Image> Best value
                </button>
                <div className="express">
                  <p className="exp-p">Express</p>
                  <p className="date">Est. 5 days</p>
                </div>
              </div>
              <div className="distance">
                <div className="delhi-distance">
                  <Image src={Location} alt="location"></Image>
                  <p>110003, Delhi</p>
                </div>
                <div className="hifen"></div>
                <Image className="plane-img" src={Plane} alt="plane"></Image>
                <div className="hifen"></div>
                <div className="sanghi-distance">
                  <Image src={Location} alt="location"></Image>
                  <p>200080, Shanghai</p>
                </div>
              </div>
            </div>
            <div className="primetime">
              <div className="primetime-left">
                <Image src={Frame} alt="frame"></Image>
                <p>Primetime Worldwide</p>
              </div>
              <div className="primetime-right">
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={BlueStar} alt="blue"></Image>
                <Image src={WhiteStar} alt="white"></Image>
              </div>
            </div>
          </div>
          <div className="last-div-sidebar"></div>
          <div className="last-div-right">
            <p className="last-div-right-p">
              $ 3,982.<span>63</span>
            </p>
            <div className="last-div-down">
              <button>Select</button>
              <p>View details</p>
            </div>
          </div>
        </div>

        <div className="last-div-div4">
          <div className="last-div-left">
            <div className="last-div-left-upper">
              <div className="express-div">
                <button className="best-value">
                  {" "}
                  <Image src={Ellipse} alt="ellipse"></Image> Best value
                </button>
                <div className="express">
                  <p className="exp-p">Express</p>
                  <p className="date">Est. 5 days</p>
                </div>
              </div>
            </div>
          </div>
          <div className="last-div-sidebar4"></div>
          <div className="last-div-right">
            <p className="last-div-right-p">
              $ 3,982.<span>63</span>
            </p>
          </div>
        </div>

      </div>
      <div className="link">
        <button ><Link href="/" style={{color: 'white', textDecoration: 'none'}}>First page</Link></button>
        <button><Link href="/secondframe" style={{color: 'white', textDecoration: 'none'}}>Second Page</Link></button>
        <button><Link href="/thirdframe" style={{color: 'white', textDecoration: 'none'}}>Third Page</Link></button>
      </div>
    </div>
  );
}
